# What is an array?

An Array stores contiguous data of any given type. 

It doesn't allow data of other types.


# List

A list can store any type of data like mixed data, int, string, etc

Data analytics -> A lot of arrays and series of data

Like `math`, there are many modules given by python to perform complicated tasks.

One of the most important modules is `numpy`

`numpy` example: m x n values of matrix. Let's explore docs demos

In [5]:
import numpy as np

In [6]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [7]:
a.shape

(2, 3)

`shape` is not a function as it doesn't have ()

In [8]:
a = np.array([1, 2, 3, 4, 5, 6])

In [9]:
a

array([1, 2, 3, 4, 5, 6])

In [10]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [11]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
a[2, 3] # should be 12

np.int64(12)

In [14]:
a = np.array([1, 2, 3, 4, 5, 6])
a[:3]

array([1, 2, 3])

^ This is called array splicing.

In [15]:
a = np.array([1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6])
a[:3]

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [18]:
a = np.array([[1, 2, 3, 4, 5, 6], 
             [1, 2, 3, 4, 5, 6],
             [1, 2, 3, 4, 5, 6],
             [1, 2, 3, 4, 5, 6]])
a[:3]

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])